language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - ./bin/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    - SYMFONY_DEPRECATIONS_HELPER=29

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_install:
  - composer self-update

install:
  - composer install
  - ./bin/phpunit install
  - ./bin/console doctrine:database:create --env=test
  - ./bin/console doctrine:migrations:migrate --env=test

script:
  - ./bin/phpunit
  - ./bin/console lint:yaml config
  - ./bin/console lint:twig templates
  - ./bin/console security:check
  - ./bin/console doctrine:schema:validate --skip-sync --no-interaction
